name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest -q
    continue-on-error: true

  notify-sentinel:
    needs: test
    if: needs.test.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Sentinel of CI failure
        run: |
          curl -sS -X POST "$SENTINEL_URL/webhooks/ci/failure" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: workflow_run" \
            -d @- <<'JSON'
          {
            "repo": "Error-Get",
            "failing_test": "tests/test_math_ops.py::test_add",
            "logs": "pytest failure (redacted)",
            "diff": "diff --git a/app_demo/math_ops.py b/app_demo/math_ops.py\n-                return a - b\n+                return a + b\n"
          }
          JSON
        env:
          SENTINEL_URL: ${{ secrets.SENTINEL_URL }}
